/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.NoSuchElementException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Cita;
import modelo.GestorDatos;

/**
 * Panel gráfico que permite registrar observaciones médicas
 * asociadas a una cita previamente creada.
 * 
 * @author Mauricio León Bermúdez C5G444
 */
public class VistaRegistroObservacionesMedicas extends javax.swing.JPanel {

    private GestorDatos gestorDatos;

    /**
     * Constructor del panel.
     * Recibe una instancia del gestor de datos para obtener las citas.
     * 
     * @param gestorDatos Objeto encargado de la administración de citas.
     */
    public VistaRegistroObservacionesMedicas(GestorDatos gestorDatos) {
        this.gestorDatos = gestorDatos;
        initComponents();
    }

    /**
     * Carga todas las citas activas en el comboBox.
     * Si la cita seleccionada ya tiene observaciones,
     * las escribe automáticamente en el campo de texto.
     * 
     * Muestra un mensaje si no existen citas activas.
     */
    public void cargarCitas() {
        comboCitas.removeAllItems();

        ArrayList<Cita> citasActivas;
        try {
            citasActivas = gestorDatos.getCitasPorEstado(true);

            for (Cita c : citasActivas) {
                comboCitas.addItem(
                        c.getDia() + " - " + c.getHora() + " - " + c.getFecha()
                        + " - " + c.getPaciente().getId() + " - " + c.getPaciente().getNombre()
                );
            }

            Object citaSel = getComboCitas().getSelectedItem();

            if (citaSel != null) {
                String[] partes = citaSel.toString().split(" - ");
                String dia = partes[0];
                String hora = partes[1];
                LocalDate fecha = LocalDate.parse(partes[2]);
                int id = Integer.parseInt(partes[3]);
                String nombre = partes[4];

                Cita c = gestorDatos.getCitaPorDatos(dia, hora, fecha, id, nombre);

                // Mostrar observaciones
                if (c.getObservaciones() != null && !c.getObservaciones().isBlank()) {
                    txtObservaciones.setText(c.getObservaciones());
                } else {
                    txtObservaciones.setText("");
                }
            }

        } catch (NoSuchElementException ex) {
            // No citas = no llena comboBox
            JOptionPane.showMessageDialog(this,
                    "No hay citas activas registradas",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public GestorDatos getGestorDatos() {
        return gestorDatos;
    }

    public JButton getBtnMenu() {
        return btnMenu;
    }

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public JComboBox<String> getComboCitas() {
        return comboCitas;
    }

    public JTextField getTxtObservaciones() {
        return txtObservaciones;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboCitas = new javax.swing.JComboBox<>();
        txtObservaciones = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CITA MEDICA A REGISTRAR OBSERVACIONES");
        jLabel1.setToolTipText("");

        btnRegistrar.setText("Registrar");

        btnMenu.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(comboCitas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegistrar)
                        .addGap(78, 78, 78)
                        .addComponent(btnMenu)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnMenu))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
