/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;

/**
 *
 * @author Meowricio
 */
public class VistaMenu extends javax.swing.JPanel {
    
    //private JButton btnCitas = new JButton("Citas");
    //private JButton btnPacientes = new JButton("Pacientes");

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
    }

    public JButton getBtnCitas() {
        return btnCitas;
    }

    public JButton getBtnRegistro() {
        return btnRegistroPaciente;
    }
    
    public JButton getBtnMenu() {
        return btnMenu;
    }

    public JButton getBtnRegistroMedico() {
        return btnRegistroMedico;
    }

    public JButton getBtnRegistroPaciente() {
        return btnRegistroPaciente;
    }

    public JButton getBntRegistrarObservacion() {
        return bntRegistrarObservacion;
    }

    public JButton getBtnArchivo() {
        return btnArchivo;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public JButton getBtnReportes() {
        return btnReportes;
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistro1 = new javax.swing.JButton();
        btnCitas = new javax.swing.JButton();
        btnRegistroPaciente = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnRegistroMedico = new javax.swing.JButton();
        bntRegistrarObservacion = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnArchivo = new javax.swing.JButton();

        btnRegistro1.setText("Registro");
        btnRegistro1.setAlignmentY(0.0F);

        btnCitas.setText("Citas");
        btnCitas.setAlignmentY(0.0F);

        btnRegistroPaciente.setText("Registrar Paciente");
        btnRegistroPaciente.setAlignmentY(0.0F);

        btnMenu.setText("Regresar");
        btnMenu.setAlignmentY(0.0F);

        btnRegistroMedico.setText("Registrar Medico");
        btnRegistroMedico.setAlignmentY(0.0F);

        bntRegistrarObservacion.setText("Registrar Observacion");

        btnReportes.setText("Reportes");

        btnEliminar.setText("Eliminar/Cancelar");

        btnArchivo.setText("Generar Archivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistroMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistroPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntRegistrarObservacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnArchivo)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroMedico)
                    .addComponent(btnCitas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistroPaciente)
                    .addComponent(bntRegistrarObservacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReportes)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(btnArchivo)
                .addGap(18, 18, 18)
                .addComponent(btnMenu)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRegistrarObservacion;
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnCitas;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegistro1;
    private javax.swing.JButton btnRegistroMedico;
    private javax.swing.JButton btnRegistroPaciente;
    private javax.swing.JButton btnReportes;
    // End of variables declaration//GEN-END:variables
}
