/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.util.ArrayList;
import java.util.NoSuchElementException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import modelo.Cita;
import modelo.GestorDatos;
import modelo.Medico;
import modelo.Paciente;

/**
 *
 * @author Meowricio
 */
public class VistaEliminar extends javax.swing.JPanel {
    
    private GestorDatos gestorDatos;
    /**
     * Creates new form VistaEliminar
     */
    public VistaEliminar(GestorDatos gestorDatos) {
        this.gestorDatos = gestorDatos;
        initComponents();      
    }
    
    public void cargarComboBox() {
        cargarPacientes();
        cargarMedicos();
        cargarCitas();
    }
    private void cargarPacientes() {
        comboPacientes.removeAllItems();
        ArrayList<Paciente> lista = gestorDatos.getPacientes();
        
        if(lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay Pacientes Registrados", "Error", JOptionPane.ERROR_MESSAGE);
        }
        for (Paciente p : lista) {
            comboPacientes.addItem(p.getId() + " - " + p.getNombre());
        }
    }
    
    private void cargarMedicos() {
        comboMedicos.removeAllItems();
        ArrayList<Medico> lista = gestorDatos.getMedicos();
        
        if(lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay Médicos Registrados", "Error", JOptionPane.ERROR_MESSAGE);
        }
        for (Medico m : lista) {
            comboMedicos.addItem(m.getCodigo() + " - " + m.getNombre() + " (" + m.getEspecialidad() + ")");
        }
    }
    
    private void cargarCitas() {
        comboCitas.removeAllItems();
        StringBuilder msg = new StringBuilder();

        try {
            ArrayList<Cita> lista = gestorDatos.getCitasPorEstado(true);

            for (Cita c : lista) {
                comboCitas.addItem(c.getPaciente().getId() + " | " + c.getMedico().getCodigo() + " | " + c.getFecha() + " | " + c.getHora());
            }
        } catch (NoSuchElementException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void refrescarCitas() {
        cargarCitas();
    }

    public GestorDatos getGestorDatos() {
        return gestorDatos;
    }

    public JButton getBtnCita() {
        return btnCita;
    }

    public JButton getBtnMedico() {
        return btnMedico;
    }

    public JButton getBtnMenu() {
        return btnMenu;
    }

    public JButton getBtnPaciente() {
        return btnPaciente;
    }

    public JComboBox<String> getComboCitas() {
        return comboCitas;
    }

    public JComboBox<String> getComboMedicos() {
        return comboMedicos;
    }

    public JComboBox<String> getComboPacientes() {
        return comboPacientes;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboPacientes = new javax.swing.JComboBox<>();
        comboMedicos = new javax.swing.JComboBox<>();
        comboCitas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnPaciente = new javax.swing.JButton();
        btnMedico = new javax.swing.JButton();
        btnCita = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Pacientes Registrados:");

        jLabel2.setText("Medicos Registrados:");

        jLabel3.setText("Citas Registradas:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eliminar Registros de Datos");

        btnPaciente.setText("Eliminar Paciente");

        btnMedico.setText("Eliminar Medico");

        btnCita.setText("Cancelar Cita");

        btnMenu.setText("Volver");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ID PACIENTE | ID MEDICO | FECHA | HORA");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMedico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCita, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMedicos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboCitas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboPacientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboPacientes)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboMedicos)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCita)
                    .addComponent(btnMedico)
                    .addComponent(btnPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenu)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCita;
    private javax.swing.JButton btnMedico;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JComboBox<String> comboCitas;
    private javax.swing.JComboBox<String> comboMedicos;
    private javax.swing.JComboBox<String> comboPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
